### ISSUE TITLE
Rename this repository to ckeditor5-cloud-services

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-cloud-services#14]
As in title. This repository should be called `ckeditor5-cloud-services`.

**Comment by pjasiun** [comment]
I renamed repository, however all usage and configuration need to be changed.

**Comment by Reinmar** [comment]
This is done. The last bit will be deprecating ckeditor5-cloudservices, but I need to do that after the new version is released, so after beta.2.
